spring.application.name=iot

spring.datasource.url=jdbc:mysql://localhost:3306/iot
spring.datasource.username=root
spring.datasource.password=08022004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver